// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZ2hZuvZXlIrzzRpK-HDE7uRfdv8ppw8',
    appId: '1:26913522366:web:31181a4071ff567492d4ef',
    messagingSenderId: '26913522366',
    projectId: 'winform-dc210',
    authDomain: 'winform-dc210.firebaseapp.com',
    databaseURL: 'https://winform-dc210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'winform-dc210.appspot.com',
    measurementId: 'G-DV5ESE1SNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10LRKyDmwHVZKQJf-pPflRw0FHXC7D0o',
    appId: '1:26913522366:android:8f0e99cf3e09256892d4ef',
    messagingSenderId: '26913522366',
    projectId: 'winform-dc210',
    databaseURL: 'https://winform-dc210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'winform-dc210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1MpasxNDmPNNZNMG4kyUSHHmZpvh5xy4',
    appId: '1:26913522366:ios:ea5ae042f70cd3c592d4ef',
    messagingSenderId: '26913522366',
    projectId: 'winform-dc210',
    databaseURL: 'https://winform-dc210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'winform-dc210.appspot.com',
    iosBundleId: 'com.example.movieTheater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1MpasxNDmPNNZNMG4kyUSHHmZpvh5xy4',
    appId: '1:26913522366:ios:ea5ae042f70cd3c592d4ef',
    messagingSenderId: '26913522366',
    projectId: 'winform-dc210',
    databaseURL: 'https://winform-dc210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'winform-dc210.appspot.com',
    iosBundleId: 'com.example.movieTheater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiZ2hZuvZXlIrzzRpK-HDE7uRfdv8ppw8',
    appId: '1:26913522366:web:5c66b3c6bce7f31792d4ef',
    messagingSenderId: '26913522366',
    projectId: 'winform-dc210',
    authDomain: 'winform-dc210.firebaseapp.com',
    databaseURL: 'https://winform-dc210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'winform-dc210.appspot.com',
    measurementId: 'G-496SP7SEFS',
  );

}